version: '3'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=p360.info,www.p360.info,p360.club,www.p360.club
      - LETSENCRYPT_HOST=p360.info,www.p360.info,p360.club,www.p360.club
      - LETSENCRYPT_EMAIL=aaaler@gmail.com



networks:
  default:
    external:
      name: webproxy

