version: '2.4'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 50m
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=p360.club,www.p360.club #,p360.info,www.p360.info
      - VIRTAUL_PORT=80
      - LETSENCRYPT_HOST=p360.club,www.p360.club #,p360.info,www.p360.info
      - LETSENCRYPT_EMAIL=aaaler@gmail.com



networks:
  default:
    external:
      name: webproxy

